{
 "title": "Celo Network Validator Exporter (v1.1.1)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "signer", "label": "signer", "query": "label_values(signer)" }
  ]
 },
 "panels": [
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Queried from the node the exporter is connected to",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "repeat": "signer",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celochain_epoch_current{signer=~\"$signer\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Latest Block",
   "type": "stat",
   "description": "Queried from the node the exporter is connected to",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "repeat": "signer",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celochain_latest_block_number{signer=~\"$signer\"}",
     "legendFormat": "Latest Block"
    }
   ]
  },
  {
   "title": "Epoch Countdown (Blocks)",
   "type": "stat",
   "description": "Queried from the node the exporter is connected to",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "repeat": "signer",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celochain_epoch_countdown_blocks{signer=~\"$signer\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Epoch Countdown (Time)",
   "type": "stat",
   "description": "Queried from the node the exporter is connected to",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "repeat": "signer",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celochain_epoch_countdown_seconds{signer=~\"$signer\"}",
     "legendFormat": "Epoch Countdown (Time)"
    }
   ]
  },
  {
   "title": "Validator Signer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "repeat": "signer",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celochain_web3_client_info{signer=~\"$signer\"}",
     "legendFormat": "{{signer}}"
    }
   ]
  },
  {
   "title": "Consecutive Downtime Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "blocks" }
   ],
   "targets": [
    {
     "expr": "celochain_downtime_blocks_consecutive{signer=~\"$signer\"}",
     "legendFormat": "{{signer}}"
    },
    {
     "expr": "celochain_downtime_blocks_consecutive_slow{signer=~\"$signer\"}",
     "legendFormat": "Slow Reset {{signer}}"
    }
   ]
  },
  {
   "title": "Downtime Block Rate",
   "type": "graph",
   "description": "If downtime occurs the rate is expected to be at 0.2 blocks/seconds (based on 5s per Block). Higher values can appear if prometheus is not querying at a 5s interval or a scrape was delayed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "blocks/s" }
   ],
   "targets": [
    {
     "expr": "irate(celochain_downtime_blocks_total{signer=~\"$signer\"}[1m])",
     "legendFormat": "{{signer}}"
    }
   ]
  }
 ]
}